class AppIcons {
  AppIcons._();

  static const String recripLogo = 'assets/images/recrip.png';
  static const String whatsappLogo = 'assets/icons/WhatsappLogo.svg';
  static const String alarmClockTab = 'assets/icons/alarm-clock_tab.svg';
  static const String backButton = 'assets/icons/back-button.svg';
  static const String bellRing = 'assets/icons/bell-ring.svg';
  static const String bell = 'assets/icons/bell.svg';
  static const String bookCheckTab = 'assets/icons/book-check_tab.svg';
  static const String calendarDays = 'assets/icons/calendar-days.svg';
  static const String calendarSync = 'assets/icons/calendar-sync.svg';
  static const String chartColumnBig = 'assets/icons/chart-column-big.svg';
  static const String chartPie = 'assets/icons/chart-pie.svg';
  static const String closeButton = 'assets/icons/close-button.svg';
  static const String creditCard = 'assets/icons/credit-card.svg';
  static const String dashboard = 'assets/icons/dashboard.svg';
  static const String download = 'assets/icons/download.svg';
  static const String dropdownDown = 'assets/icons/dropdown_down.svg';
  static const String edit = 'assets/icons/edit.svg';
  static const String email = 'assets/icons/email.svg';
  static const String eyeClose = 'assets/icons/eye-close.svg';
  static const String eyeOpen = 'assets/icons/eye-open.svg';
  static const String globe = 'assets/icons/globe.svg';
  static const String headset = 'assets/icons/headset.svg';
  static const String logOut = 'assets/icons/log-out.svg';
  static const String menu = 'assets/icons/menu.svg';
  static const String renew = 'assets/icons/renew.svg';
  static const String search = 'assets/icons/search.svg';
  static const String settings = 'assets/icons/settings.svg';
  static const String shieldXTab = 'assets/icons/shield-x_tab.svg';
  static const String trash = 'assets/icons/trash.svg';
  static const String upload = 'assets/icons/upload.svg';
  static const String usersRound = 'assets/icons/users-round.svg';
  static const String usersTab = 'assets/icons/users_tab.svg';
  static const String addCustomer = 'assets/icons/add-customer.svg';
  static const String trendingUp = 'assets/icons/trending-up.svg';
  static const String clock = 'assets/icons/clock.svg';
  static const String circleCheck = 'assets/icons/circle-check.svg';
}
